### PR TITLE
Upgrade jackson to 2.9.x

### PR DESCRIPTION
**Pull request by JamieMagee**
This is mostly a straightforward change of version number, and changing the imported packages. However, there is one test failing with these changes, `ReconnectionTest`. I've looked into why it's failing, and as far as I can see `JsonActivityFeedProcessor#process` isn't throwing an `IOException`. 

I've spent some time debugging, but would appreciate some input from someone who knows the codebase better.

### CODE REVIEW

**Comment by jcodagnone** [comment]
My first reaction is whether we should keep support of both versions, at least for the model.

Probably the serializers are the worst part but maybe if we split them in two projects maybe we can deal with them. I have to think a bit if we can have both versions.

**Comment by JamieMagee** [comment]
I'm not sure what the benefit of staying with jackson 1.x is. Version `1.8` was released in April 2011, and even the latest release of the 1.x series, `1.9.13` was released in July 2013.

I can possibly see a point with easing the upgrade route for consumers of your library. If you want to use semantic versioning, you might need to increment the major version number to 3.x. It might be an easier option to maintain a 2.x and 3.x version and backport fixes.

**Comment by JamieMagee** [comment]
I managed to fix the `ReconnectionTest`

**Comment by JamieMagee** [comment]
@jcodagnone Any decision regarding this change?

**Comment by JamieMagee** [comment]
@jcodagnone I resolved the conflicts, and upgraded jackson to `2.8.7`. Have you given this upgrade any further thought?

**Comment by jcodagnone** [comment]
I've migrating some other apps to support both versions of jackson and to gain the knowloadge.

**Comment by francisaltomare** [comment]
Any chance on this being merged in? We're looking into doing this as well.

**Comment by JamieMagee** [comment]
I've resolved the merge conflicts, and bumped the targeted jackson version from `2.8.8` to `2.9.0`.

**Pull request closed without merging**
